FROM python:latest

LABEL author="Breno"

WORKDIR /

RUN pip install --upgrade pip

COPY . /

RUN pip install -r requirements.txt

EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]